'use strict';

const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');
const yaml = require('js-yaml');
const jehm = require('./jehm');
const { JEHM_FILE, JEXT_MANIFEST } = require('./spec');
const { fail, ok, step, warn } = require('./util');

// Regenerate <marketplaceDir>/marketplace.yaml from the .jext packages in
// <marketplaceDir>/<distDir> (default "dist"). The app reads this index to
// browse, then downloads the referenced .jext to install.
function index(marketplaceDir, opts = {}) {
  const root = path.resolve(marketplaceDir || '.');
  const distName = opts.dist || 'dist';
  const distDir = path.join(root, distName);
  if (!fs.existsSync(distDir)) fail(`no ${distName}/ folder in ${root} — pack extensions into it first`);

  const jexts = fs
    .readdirSync(distDir)
    .filter((f) => f.endsWith('.jext'))
    .sort();
  if (!jexts.length) warn(`no .jext files in ${distName}/`);

  // Preserve the marketplace's own header fields if an index already exists.
  const indexPath = path.join(root, 'marketplace.yaml');
  let top = { name: 'JCode Marketplace', publisher: 'jcode', version: '1.0.0', description: 'Registry of installable JCode extensions (.jext packages).' };
  if (fs.existsSync(indexPath)) {
    try {
      const prev = yaml.load(fs.readFileSync(indexPath, 'utf8')) || {};
      for (const k of ['name', 'publisher', 'version', 'description']) if (prev[k]) top[k] = prev[k];
    } catch (_) {
      /* fall back to defaults */
    }
  }

  const extensions = [];
  for (const file of jexts) {
    const zip = new AdmZip(path.join(distDir, file));
    const jehmEntry = zip.getEntry(JEHM_FILE);
    if (!jehmEntry) {
      warn(`${file}: no ${JEHM_FILE} — skipped`);
      continue;
    }
    const { header } = jehm.parse(zip.readAsText(jehmEntry), `${file}!${JEHM_FILE}`);
    const errs = jehm.validateHeader(header);
    if (errs.length) {
      warn(`${file}: invalid header (${errs[0]}) — skipped`);
      continue;
    }
    let fingerprint = null;
    const manEntry = zip.getEntry(JEXT_MANIFEST);
    if (manEntry) {
      try {
        fingerprint = (JSON.parse(zip.readAsText(manEntry)).fingerprint) || null;
      } catch (_) {
        /* ignore */
      }
    }
    const entry = {
      uniqueName: header.uniqueName,
      name: header.name,
      publisher: header.publisher || null,
      type: header.type,
      version: header.version,
      category: header.category || null,
      subcategory: header.subcategory || null,
      shortDescription: header.shortDescription || null,
      minJCodeVersion: header.minJCodeVersion,
      targetJCodeVersion: header.targetJCodeVersion,
      jext: `${distName}/${file}`,
      fingerprint: fingerprint,
    };
    if (header.authors) entry.authors = header.authors;
    if (header.requires) entry.requires = header.requires;
    if (header.suggests) entry.suggests = header.suggests;
    if (header.supportedDistros) entry.supportedDistros = header.supportedDistros;
    if (header.supportedArches) entry.supportedArches = header.supportedArches;
    if (header.images) entry.images = header.images;
    // Publish the package icon out to dist/icons/ so the app can show it before install
    // (the rest of the package's media only exists inside the .jext).
    if (header.images && header.images.icon) {
      const iconRel = header.images.icon;
      const iconEntry = zip.getEntry(iconRel);
      if (iconEntry) {
        const ext = path.extname(iconRel) || '.png';
        const iconsDir = path.join(distDir, 'icons');
        fs.mkdirSync(iconsDir, { recursive: true });
        const iconName = `${header.uniqueName}${ext}`;
        fs.writeFileSync(path.join(iconsDir, iconName), iconEntry.getData());
        entry.icon = `${distName}/icons/${iconName}`;
      } else {
        warn(`${file}: images.icon "${iconRel}" not found in package`);
      }
    }
    extensions.push(entry);
    step(`indexed ${header.uniqueName} ${header.version}`);
  }

  extensions.sort((a, b) => a.uniqueName.localeCompare(b.uniqueName));
  const out = Object.assign({}, top, { extensions });
  const header =
    '# The `extensions:` list is generated by `jext index` from dist/*.jext —\n' +
    '# edit each extension\'s .jehm and re-pack, do not hand-edit entries.\n' +
    '# The top-level fields (name/publisher/version/description) are preserved\n' +
    '# across runs, so edit those here.\n';
  const yamlText = header + yaml.dump(out, { lineWidth: 100, noRefs: true, sortKeys: false });
  fs.writeFileSync(indexPath, yamlText);
  ok(`wrote ${path.relative(process.cwd(), indexPath) || indexPath} (${extensions.length} extensions)`);
}

module.exports = { index };
